Add a script to add versions to sync configuration
tektoncd/website pull request #183
Opened 2020-10-21 13:53 UTC by afrittoli

# Changes

Add a new python script that can be used to add a new version to
the configuration of a component.
This script can be used by various projects as part of their
release process to keep the version on the website up-to-date.

Signed-off-by: Andrea Frittoli <andrea.frittoli@gmail.com>
# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/website/blob/master/CONTRIBUTING.md)
for more details._

/cc @popcor255 
/cc @AlanGreene

2020-10-21 14:52 UTC, popcor255 commented
This looks amazing. I wish I setup ci/cd for the tests. You have to give me a sec to test it on my dev environment. lol

2020-10-21 14:58 UTC, AlanGreene requested changes
Useful script! 👍 

Small issue with the default value for `project`, it should be `pipeline` instead of `pipelines`. Should we rename the config file to match / avoid confusion?

It would also be nice it the script output an error on an invalid project name instead of failing silently but that's not a blocker for this PR.

2020-10-21 14:58 UTC, AlanGreene commented on sync/versions.py
> +    'project', 'pipelines', 'Name of the component', short_name='p')
```suggestion
    'project', 'pipeline', 'Name of the component', short_name='p')
```

2020-10-21 14:58 UTC, AlanGreene commented on sync/README.md
> +    (default: 'pipelines')
```suggestion
    (default: 'pipeline')
```

2020-10-21 15:23 UTC, afrittoli commented on sync/README.md
> +    (default: 'pipelines')
Nice catch, thank you!

2020-10-21 15:42 UTC, afrittoli commented
/hold

2020-10-21 15:43 UTC, afrittoli commented
> Useful script! 👍
> 
> Small issue with the default value for `project`, it should be `pipeline` instead of `pipelines`. Should we rename the config file to match / avoid confusion?
> 
> It would also be nice if the script output an error on an invalid project name instead of failing silently but that's not a blocker for this PR.

I'll update the script to error in case of project not found

2020-10-21 15:57 UTC, afrittoli commented on sync/requirements.txt
> +ruamel.yaml==0.16.12
This change is so that we can preserve comments in the YAML config when updating them via a python script.

2020-10-21 15:59 UTC, afrittoli commented
/hold cancel

2020-10-21 16:00 UTC, afrittoli commented
The script will now log an error and exit with code 1 in case the project cannot be found.

2020-10-21 16:45 UTC, AlanGreene approved these changes
Looks good :shipit:

2020-10-21 17:02 UTC, popcor255 commented
![image](https://user-images.githubusercontent.com/1755197/96753304-adb44d80-139d-11eb-94be-5bbd522e7ef4.png)
This might be a bug with netlify, but there a duplicates of fields.

2020-10-21 17:08 UTC, afrittoli commented
> ![image](https://user-images.githubusercontent.com/1755197/96753304-adb44d80-139d-11eb-94be-5bbd522e7ef4.png)
> This might be a bug with netlify, but there a duplicates of fields.

I wonder if this is because I changed the component names in the config, and old files were left around? I though netlify would use fresh envs everytime, but maybe they are not.

It looks good on my laptop, with `letlify dev`- so I don't know which to trust now?

2020-10-21 17:14 UTC, AlanGreene commented
Good catch @popcor255, seeing it on the PR deploy preview too:
https://deploy-preview-183--tekton.netlify.app/docs/

Case sensitivity issue perhaps? e.g. `CLI` vs `cli`
Checking the build output locally again

2020-10-21 17:26 UTC, AlanGreene commented
See https://github.com/tektoncd/website/tree/81ca55da2a3ff30fcb9ef2abc36eaaa6ac1aceca/content/en/docs
![image](https://user-images.githubusercontent.com/2829095/96755085-23cea980-13ca-11eb-8d3e-b0065f767763.png)

With the updated config, content is synced to folders named in lower case and we end up with:
```
Catalog/
Concepts/
Dashboard/
Getting Started/
Pipelines/
_index.md
cli/
getting-started-overview.md
pipeline/
triggers/
```

On a case-sensitive filesystem we would have duplicates for CLI and Triggers too.

2020-10-21 17:32 UTC, afrittoli commented
OK - I think the easiest will be to revert the names there then.
The reason for changing the name was to avoid have a name matching that of the project.
When adding a new release I don't want to use the name that is displayed on the website, I'd like to use the git project name instead.
I can change the match to be on `repository` instead of `component`.

2020-10-21 17:33 UTC, afrittoli commented
/hold

2020-10-21 17:53 UTC, popcor255 commented
I have had this issue as well. Sync does not delete the old docs folder. So, even if we change the env. Everytime we change the sync we would be adding files without removing the older ones. We probably should delete the content folder whenever we redeploy.

2020-10-21 22:13 UTC, afrittoli commented
/hold cancel

2020-10-21 22:13 UTC, afrittoli commented
Preview looks good now.

2020-10-22 14:42 UTC, popcor255 commented
/lgtm

2020-10-22 16:35 UTC, merged