Add recent pipelines releases to sync config
tektoncd/website pull request #495
Opened 2023-01-24 19:19 UTC by lbernick

# Changes

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/website/blob/master/CONTRIBUTING.md)
for more details._

2023-01-24 19:35 UTC, AlanGreene requested changes
Thanks @lbernick, just 1 small change to mark the most recent release as LTS (similar to v0.41.x)

2023-01-24 19:35 UTC, AlanGreene commented on sync/config/pipelines.yaml
> +  displayName: v0.44.x
```suggestion
  displayName: v0.44.x LTS
```

2023-01-24 20:17 UTC, lbernick commented on sync/config/pipelines.yaml
> +  displayName: v0.44.x
done!

2023-01-26 15:48 UTC, AlanGreene approved these changes

2023-01-26 16:50 UTC, geriom reviewed
/lgtm

2023-01-26 16:52 UTC, merged