Initial revision of SLSA blog post.
tektoncd/website pull request #537
Opened 2023-04-17 15:03 UTC by bendory

# Changes

Added SLSA blog post.

This blog initially appeared at https://opensource.googleblog.com/2023/03/getting-to-slsa-level-2-with-tekton-and-tekton-chains.html

Note: do not merge this PR until the corresponding example has been merged: https://github.com/tektoncd/chains/pull/775) 

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [N/A] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

2023-04-17 15:48 UTC, bendory commented
Preview is now available at: https://deploy-preview-537--tekton.netlify.app/blog/2023/04/17/getting-to-slsa-level-2-with-tekton-and-tekton-chains/

2023-04-17 15:49 UTC, bendory commented
/do-not-merge

confirm that this PR merges first: https://github.com/tektoncd/chains/pull/775

2023-04-17 20:03 UTC, geriom approved these changes

2023-04-17 20:49 UTC, geriom requested changes
Meant to request changes instead of approve 😅

2023-04-18 15:42 UTC, bendory commented on content/en/blog/2023/slsa-2/index.md
> +Let's follow through with [an example][example-repo], which has the following files:
👍

2023-04-18 16:29 UTC, geriom approved these changes
Thank you!

2023-04-24 12:35 UTC, abayer commented
/lgtm

2023-04-24 12:36 UTC, merged