blog(add article): tekton + tracetest
tektoncd/website pull request #557
Opened 2023-08-10 13:55 UTC by adnanrahic

# Changes

This PR adds a new blog post for using distributed tracing for testing with Tracetest and automating tests with Tekton.
Based on [this docs page in Tracetest docs](https://docs.tracetest.io/ci-cd-automation/tekton-pipeline). 

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/website/blob/master/CONTRIBUTING.md)
for more details._

2023-08-10 15:29 UTC, adnanrahic commented
Thanks for responding @afrittoli !

I've set the date of the blog post to August 15th. LMK if we need to change that to something else. 😄

2023-08-14 13:02 UTC, adnanrahic commented
Hey @AlanGreene  @geriom ! Wanted to touch base and ask if tomorrow is a good date to publish the blog post. If not, let me know and we can work out another date. 😄

2023-08-15 15:17 UTC, geriom requested changes
Sorry fro the delay. Added a couple of suggestions.

2023-08-15 15:17 UTC, geriom commented on content/en/blog/2023/distributed-traces-for-testing-with-tekton-pipelines-and-tracetest/index.md
> +```bash
Provide instructions for all every OS. Something like this should work:

```go-html-template
{{< tabs >}}

{{< tab header="MacOS" lang="bash" >}}
brew install kubeshop/tracetest/tracetest
{{< /tab >}}


{{< tab header="Linux" lang="bash" >}}
curl -L https://raw.githubusercontent.com/kubeshop/tracetest/main/install-cli.sh | bash
{{< /tab >}}


{{< tab header="Windows" lang="bash" >}}
choco source add --name=kubeshop_repo --source=https://chocolatey.kubeshop.io/chocolatey ; choco install tracetest
{{< /tab >}}

{{< /tabs >}}
```

2023-08-16 13:20 UTC, geriom approved these changes

2023-08-17 11:58 UTC, adnanrahic commented
Hey @geriom 👋 
Thanks for approving the PR!
Wanted to ask when this could be merged? I am not authorized to merge it myself.

2023-08-18 16:24 UTC, geriom commented
> Hey @geriom 👋 Thanks for approving the PR! Wanted to ask when this could be merged? I am not authorized to merge it myself.

I just pinged Alan on slack in case he has some time to take a look. PRs usually need two approvals to be merged.

2023-08-28 10:28 UTC, adnanrahic commented
Hey @geriom & @AlanGreene ! 👋 

I wanted to circle back to this and ping you to ask if we should update the blog post date and get it merged this week.

Alternatively, I'm happy to wait for @afrittoli to get back from PTO.

Thanks! 🙌

2023-09-07 17:39 UTC, afrittoli reviewed
Thank you!
/lgtm

2023-09-07 17:40 UTC, merged